In [31]:
import requests
import pandas as pd
df_merged=pd.DataFrame()
url = "https://www.startupwala.com/list-of-registered-companies-in-india-P"
for e in [str(x) for x in range(1,11)]:
    df_merged = df_merged.append(pd.read_html(requests.get(url+e).text)[0])
df_merged.reset_index(drop=True, inplace=True)
df_merged

,COMPANY NAME,CIN,ROC NAME,STATUS
0,TUVIS TECHNOLOGIES AND INNOVATIONS PRIVATE LIM...,U72900MH2021PTC354246,RoC-Mumbai,Active
1,ARASTU ENTERPRISES PRIVATE LIMITED,U51909MH2021PTC354247,RoC-Mumbai,Active
2,ROLFAB PRIVATE LIMITED,U29304GJ2021PTC119848,RoC-Ahmedabad,Active
3,SUN CITY TRANSPORT PRIVATE LIMITED,U60221DL2021PTC376288,RoC-Delhi,Active
4,HSL GLOBAL CARRIERS INDIA PRIVATE LIMITED,U63031MH2021PTC354248,RoC-Mumbai,Active
...,...,...,...,...
245,MEDAPALLY FARMER PRODUCER COMPANY LIMITED,U01100TG2020PTC140315,RoC-Hyderabad,Active
246,PROGRACE DATA SOLUTIONS PRIVATE LIMITED,U72900MH2020PTC339287,RoC-Mumbai,Active
247,GLORIOUS BIO CARE PRIVATE LIMITED,U24100GJ2015PTC085132,RoC-Ahmedabad,Active
248,ECOTRAIL PERSONAL CARE PRIVATE LIMITED,U24100GJ2015PTC085138,RoC-Ahmedabad,Active
249,SKRK FOOD SOLUTION (OPC) PRIVATE LIMITED,U15100DL2018OPC328442,RoC-Delhi,Active

In [32]:
df_merged[df_merged['COMPANY NAME'].str.contains('FARMER')]

,COMPANY NAME,CIN,ROC NAME,STATUS
16,BANKA MADHU FARMERS PRODUCER COMPANY LIMITED,U01400BR2021PTC050275,RoC-Patna,Active
23,SOIL AGRO FARMER PRODUCER COMPANY LIMITED,U01409MH2020PTC345226,RoC-Mumbai,Active
42,UPANJE FARMERS PRODUCER COMPANY LIMITED,U01400BR2020PTC047827,RoC-Patna,Active
53,CHASI BHAI FARMERS PRODUCER COMPANY LIMITED,U01114OR2020PTC034559,RoC-Cuttack,Active
55,SHRIRAJYOGI RAMDAS MAHARAJ FARMERS PRODUCER CO...,U01110MH2020PTC348515,RoC-Mumbai,Active
232,FARMERS HUB ORGANIC PRIVATE LIMITED,U15319UP2018PTC101527,RoC-Kanpur,Active
245,MEDAPALLY FARMER PRODUCER COMPANY LIMITED,U01100TG2020PTC140315,RoC-Hyderabad,Active

In [33]:
df_merged[df_merged['COMPANY NAME'].str.contains('FPO')]

Empty DataFrame
Columns: [COMPANY NAME, CIN, ROC NAME, STATUS]
Index: []